### ISSUE TITLE
Update GUI Fails On Yes/No Type Enviroment Variables

### ISSUE THREAD

**Issue by davegoopot** [MscrmTools/MscrmTools.EnvironmentVariableManager#1]
Steps to reproduce:

1. Create an Environment variable of type yes/no
2. Fire up XrmToolBox and the Environment Variables Manager tool
3. Click into the yes/no variable to try to change the type e.g. from "yes" to "no"

Result  = An error saying that the type is not a boolean:

![image](https://user-images.githubusercontent.com/3875290/198393012-7bc8ef75-6970-4463-908f-66e821632c9d.png)

**Comment by davegoopot** [comment]
The work around I have is:

1. Change the type to either "true" or "false" - note that you can't leave these values as Dynamics seems to want the values to be "yes" or "no"
2. Having changed to "true" or "false", but not pressed the update button, you can now change the value to "yes" or "no"
3. Press the update button to save.

**Comment by davegoopot** [comment]
From https://learn.microsoft.com/en-gb/power-apps/maker/data-platform/EnvironmentVariables : 

> Validation of environment variable values happens within the user interfaces and within the components that use them, but not within Dataverse. Therefore ensure proper values are set if they're being modified through code.

Investigating what happens on https://make.powerapps.com/ when you set a current value of a boolean field, it sets the environment variable value to "yes" or "no". My suggestion is that this plugin should match that behaviour.

**Comment by MscrmTools** [comment]
Thank you for the investigations.
I will update the tool
